### ISSUE TITLE
Dropbox / Security

### ISSUE THREAD

**Issue by Karvovskaya** [vu-rdm-tech/storage-finder#17]
I am a bit confused by the way Security section is filled in for non-approved tools like Drobpx and Google drive.  (Why Dropbox for Buisness? They also have individual plans https://www.dropbox.com/plans )
Saying "Not suitable for research data" is confusing - why not suitable? Technically its perfectly suitable. Maybe reformulate like this: "not recommended for storage of research data and any work related data by VU employees"?
Same with Google drive: "Not suitable for research data, especially not for personal data (Low)" - I find this confusing

**Comment by Elisa-on-GitHub** [comment]
Dropbox was removed from the storage finder and this has been amended for Google Drive.
