### ISSUE TITLE
Betekent archiving ook een DOI?

### ISSUE THREAD

**Issue by Elisa-on-GitHub** [vu-rdm-tech/storage-finder#23]
Gaat vooral over Yoda en OSF. Doordat er een feature met archiving instaat, gaat dat deze vraag oproepen. Hoe zetten we dit er duidelijk in? Kent Yoda automatisch DOIs toe of moet je die handmatig invoegen? Komt ook uit feedback gebruiker

**Comment by peer35** [comment]
Op de Yoda help site staat informatie over archiving en publishing die dit hopelijk duidelijk maakt:
https://yoda.vu.nl/site/getting-started/archiving.html
https://yoda.vu.nl/site/getting-started/publishing.html

--> Standaard zijn datasets in de Vault alleen zichtbaar voor je eigen groep (en de datamanager). Bij publicatie wordt een DOI automatisch toegekend en met de metadata gepubliceerd op datacite.org

**Comment by peer35** [comment]
Om het ingewikkelder te maken is gepubliceerde data in Yoda dus altijd ook "gearchiveerd" (in de zin van niet-wijzigbaar).

Maar: in OSF kan je een project met data publiceren (incl. DOI), maar kan je die data achteraf gewoon wijzigen. Data wordt in OSF dus niet gearchiveerd, maar wel gepubliceerd. Uitzondering daarop zijn  preregistrations die zijn niet-wijzigbaar.

**Comment by peer35** [comment]
Wat we voornamelijk missen is een link naar een goede pagina over de archivering en publicatietools, DataverseNL staat (en hoort?) niet op de Storagefinder.

We wilden met het archiving/publishing filter voornamelijk Yoda en OSF onderscheiden van de andere opties.

**Comment by Elisa-on-GitHub** [comment]
Dit is nogal mosterd na de maaltijd, maar ik heb dit uiteindelijk anders opgelost en sluit daarom dit issue
