### ISSUE TITLE
Meer informatie over backup en versioning?

### ISSUE THREAD

**Issue by Elisa-on-GitHub** [vu-rdm-tech/storage-finder#9]
Commentaar uit RDM-overleg: alleen "Yes" bij backup (en, denk ik, versioning) geeft niet genoeg informatie.

**Comment by Karvovskaya** [comment]
Note that there is a difference between how SURF Drive is filled in: "Back-up: SURF cloud service with daily backup (30 days to retrieve). The VU does not make backups of files stored in SURFdrive" and Group Drive "Back-up: Yes"
I would say that only YES is too little - it would be good at least to have a link for more information
